#!/bin/sh
#
# @name Holybro X500 full sensor stack (flow, downward rangefinder, 2D lidar, mono cam)
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=holybro_x500}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

echo "Disabling Sim GPS"
param set-default SYS_HAS_GPS 0
param set-default SIM_GPS_USED 0
param set-default EKF2_GPS_CTRL 0

echo "Optical flow + rangefinder navigation (no GPS, no baro)"
param set-default EKF2_OF_CTRL 1
param set-default EKF2_RNG_CTRL 1
param set-default EKF2_HGT_REF 2
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_MAG_TYPE 5
param set-default EKF2_SYNT_MAG_Z 0
param set-default SENS_MAG_MODE 0
param set-default SENS_IMU_MODE 1

echo "Arming config for GPS-denied autonomous sim"
param set-default COM_RC_IN_MODE 1
param set-default COM_ARM_WO_GPS 1
param set-default COM_HOME_EN 0
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0
param set-default COM_ARM_BAT_MIN -1
param set-default SIM_BAT_ENABLE 1
param set-default BAT1_V_EMPTY 3.5
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_N_CELLS 4
param set-default MAV_0_BROADCAST 1
